/**
* \file
* \brief This file is an autogenerated function prototypes header file.
*
* WARNING: This file is automatically generated. Any changes will be lost.
*/

#ifndef _UTIL_FUNCTIONS_H_
#define _UTIL_FUNCTIONS_H_

/* declared in ./absorb_file.c */
extern
int absorb_file
  (const char* path, unsigned char** buf, unsigned* buflen)
  __attribute__ ((warn_unused_result));

/* declared in ./absorb_file.c */
extern
char* dup_file_string
  (char* path)
  __attribute__ ((warn_unused_result));

/* declared in ./base64.c */
extern
int b64_encodedlength
  (int l)
  __attribute__ ((warn_unused_result));

/* declared in ./base64.c */
extern
char* b64_encode
  (void* _data, int datalength, char* out)
  __attribute__ ((warn_unused_result));

/* declared in ./base64.c */
extern
char* b64_encode_spaced
  (void* _data, unsigned size, char* out)
  __attribute__ ((warn_unused_result));

/* declared in ./base64.c */
extern
int b64_decodedlength
  (char* data)
  __attribute__ ((warn_unused_result));

/* declared in ./base64.c */
extern
char* b64_decode
  (char* data, char* out)
  __attribute__ ((warn_unused_result));

/* declared in ./chibihash64.c */
extern
uint64_t
chibihash64
  (const void *keyIn, long len, uint64_t seed)
  __attribute__ ((warn_unused_result));

/* declared in ./chibihash64.c */
extern
uint32_t
chibihash32
  (const void *keyIn, long len)
  __attribute__ ((warn_unused_result));

/* declared in ./chibihash64.c */
extern
uint16_t
chibihash16
  (const void *keyIn, long len)
  __attribute__ ((warn_unused_result));

/* declared in ./chibihash64.c */
extern
int main
  (int argc, char* argv[])
  __attribute__ ((warn_unused_result));

/* declared in ./dehexify_inplace.c */
extern
void dehexify_inplace
  (char* str, unsigned* resultlength);

/* declared in ./flogmem.c */
extern
void flogmem_colwidth
  (FILE* file, unsigned colwidth, const void* _mem, unsigned size);

/* declared in ./flogmem.c */
extern
void flogmem
  (FILE* file, const void* mem, unsigned size);

/* declared in ./flogmem.c */
extern
void logmem
  (const void* mem, unsigned size);

/* declared in ./hexcodon.c */
extern
unsigned hexcodon
  (uint8_t high, uint8_t low)
  __attribute__ ((warn_unused_result));

/* declared in ./ipv4_parse.c */
extern
int ipv4_parse
  (const char* string, uint32_t* address)
  __attribute__ ((warn_unused_result));

/* declared in ./ipv4_parse.c */
extern
char* ipv4_tostring
  (uint32_t address)
  __attribute__ ((warn_unused_result));

/* declared in ./logmsg.c */
extern
void logmsg
  (unsigned severity, char* fmt, ...);

/* declared in ./memdup.c */
extern
void* memdup
  (const void* mem, unsigned size);

/* declared in ./queryargs.c */
extern
int queryargs
  (
    unsigned argc,
    char* argv[],
    char option,
    char* longoption,
    unsigned index,
    int expectvalue,
    char** remainder,
    char** value
  )
  __attribute__ ((warn_unused_result));

/* declared in ./queryargs.c */
extern
void queryargs_
  (
    unsigned argc,
    char* argv[],
    char option,
    char* longoption,
    unsigned index,
    int expectvalue,
    char** remainder,
    char** value
  );

/* declared in ./queryargs.c */
extern
int queryargs_as_int
  (
    unsigned argc,
    char* argv[],
    char option,
    char* longoption,
    unsigned index,
    char** remainder,
    char** value
  )
  __attribute__ ((warn_unused_result));

/* declared in ./queryargs.c */
extern
char* nextarg
  (unsigned argc, char* argv[], char* arg)
  __attribute__ ((warn_unused_result));

/* declared in ./srv_clientsocket_udp.c */
extern
int srv_clientsocket_udp
  (uint32_t ip, uint16_t port)
  __attribute__ ((warn_unused_result));

/* declared in ./srv_serversocket_udp.c */
extern
int srv_serversocket_udp
  (uint32_t ip, uint16_t port)
  __attribute__ ((warn_unused_result));

/* declared in ./strxypos.c */
extern
int strxypos
  (char* string, unsigned pos, unsigned vector[ 2 ])
  __attribute__ ((warn_unused_result));

/* declared in ./write_insistent.c */
extern
int write_insistent
  (int fd, void* ptr, unsigned size, int lock)
  __attribute__ ((warn_unused_result));



#endif